### PR TITLE
Rpc class

### PR DESCRIPTION
**Pull request by tallywiesenberg**
Started working on the Rpc class. Looking for input on the concept and the implementation. Also, I seem to run into the following error `E   TypeError: issubclass() arg 1 must be a class` when running `pytest`. Any tips for this with pydantic?

### CODE REVIEW

**Comment by tallywiesenberg** [comment]
Looking to resolve the following pytest error, I'm thinking it has to do with my unfamiliarity with pydantic.
to replicate:
- activate venv
- run pytelliot from ./pytelliot/

`E       TypeError: __init__() takes 1 positional argument but 3 were given`

**Comment by clamdad** [comment]
> Looking to resolve the following pytest error, I'm thinking it has to do with my unfamiliarity with pydantic.
> 
> to replicate:
> 
> - activate venv
> 
> - run pytelliot from ./pytelliot/
> 
> 
> 
> `E       TypeError: __init__() takes 1 positional argument but 3 were given`

Hi Tally, My computer is down, but this might happen if you call a BaseModel constructor with positional arguments instead of keyword/argument pairs.

**Comment by clamdad** [comment]
After previous fix, it's now failing because URL has no value on my machine:
`url = os.getenv("NODE_URL")`
For a unit test, you should hard-code a URL that will work on any machine including the git CI server

**Comment by tallywiesenberg** [comment]
It contains a secret, however, so maybe we can add my personal node url to the github repo secrets for CI?

**Pull request merged**
